# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20170325_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('nmi', models.FloatField(default=0.0)),
                ('anc', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
