# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0002_auto_20170325_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerecord',
            name='username',
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Group'),
        ),
    ]
